name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install
        run: pnpm install
      - name: Setup Turbo caching
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: Build projects
        run: pnpm build
      - name: Authenticate Firebase
        run: pnpm exec firebase-tools use --token "${{ secrets.FIREBASE_TOKEN }}" --project "${{ secrets.FIREBASE_PROJECT }}"
      - name: Deploy to Firebase
        run: pnpm run deploy
